### ISSUE TITLE
Bug Report: Find And Replace with single backslash cannot be loaded back in

### ISSUE THREAD

**Issue by DBHeise** [gchq/CyberChef#319]
### Summary
When loading a simple find/replace where the replacement char is a backslash it cannot be loaded.

### Example
From the UI
* Add "Find / Replace" item
* Use a "\\" as the replace
* Save Recipie
Should be something like this: 
```
Find_/_Replace({'option':'Simple string','string':'test'},'\\',true,false,true)
```
* Load the recipie you just saved
* ERROR "Invalid Recipie"

**Comment by n1474335** [comment]
Good spot, thanks for raising this. I've fixed it now.

**Comment by JamieH** [comment]
@n1474335 I'm still having this issue FYI:
![image](https://user-images.githubusercontent.com/1857320/49727679-c2374300-fc68-11e8-8211-90514f4e082c.png)

Saves as:
```
Find_/_Replace({'option':'Regex','string':'\\\\'},'\\',true,false,true,false)
Find_/_Replace({'option':'Regex','string':'\\\\\\\\'},'\\\\',true,false,true,false)
```

I can make a new issue for this if you'd like?

**Comment by n1474335** [comment]
Hmm, that's weird. That save string is correct, but it doesn't load correctly. Reopening this issue.

**Comment by j433866** [comment]
Closed in #552
